[YouTube-RVX]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "raman452mth/rex-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "inotia00"
arch = "arm64-v8a"
version = "19.05.36"
included-patches = "'Custom header for YouTube'"
excluded-patches = "'Ambient mode control' 'Change start page' 'Custom Shorts action buttons' 'Custom branding icon for YouTube' 'Custom branding name for YouTube' 'Custom double tap length' 'Disable QUIC protocol' 'Disable auto audio tracks' 'Enable OPUS codec' 'Enable debug logging' 'Enable gradient loading screen' 'Layout switch' 'Settings for YouTube' 'Swipe controls' 'Translations for YouTube'"

[YouTube-anddea]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "anddea"
version = "19.05.36"
