[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
arch = "arm64-v8a"
version = "19.05.36"
included-patches = "'Enable slide to seek'"
excluded-patches = "'Announcements' 'Enable debugging' 'Enable tablet layout' 'Hide captions button' 'Hide autoplay button' 'Hide player buttons' 'Navigation buttons' 'Theme' 'Hide seekbar' 'Hide filter bar' 'Hide timestamp' 'Swipe controls'"
